on:
  push:
    branches:
      - main

name: Version

jobs:
  tag:
    name: Tag next
    timeout-minutes: 30
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_next_version.outputs.version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get next version from Cargo.toml
        id: get_next_version
        run: |
          cargo_version=$(grep '^version' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=v$cargo_version" >> $GITHUB_ENV
          echo "version=v$cargo_version" >> $GITHUB_OUTPUT

      - name: Create Tag
        id: create_tag
        run: |
          git tag $(printf "%s" ${{ env.cargo_version }})
          git push origin --tags

  release:
    name: Create Release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install ubuntu dependencies
        run: sudo apt-get install -y libgtk-3-dev

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: true

      - name: Build Release Binary
        run: |
          cargo build --release
          zip -j target/rusty_fuugbemu.zip target/release/rusty_fuugbemu
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.version }}
          release_name: Release ${{ needs.tag.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/rusty_fuugbemu.zip
          asset_name: rusty_fuugbemu.zip
          asset_content_type: application/zip





